version: '3.9'

services:
  redis:
    image: "redis:latest"
    hostname: "redis"
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    restart: unless-stopped
    ports:
      - "6379:6379"

  nest-core:
    build:
      context: .
#      dockerfile: Dockerfile  # Optional if the Dockerfile is named "Dockerfile"
    container_name: nest-core
    ports:
      - "8080:8080"
    depends_on:
      - redis
    links:
      - redis