name: Docker Image CI

on:
  push:
    branches:
      - "**"  # Runs on all branches
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history to get commit hashes properly

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Determine Commit Hash
        id: vars
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            # Use the latest commit hash when merged into main
            COMMIT_HASH=$(git rev-parse --short HEAD)
          else
            # Use the commit hash of the pushed commit in feature branches
            COMMIT_HASH=$(git rev-parse --short $GITHUB_SHA)
          fi
          echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV
          echo "Computed Commit Hash: $COMMIT_HASH"

      - name: Build and Push Docker Image
        run: |
          docker buildx build --build-arg POSTGRES_URL=${{ secrets.POSTGRES_URL }} --build-arg POSTGRES_USERNAME=${{ secrets.POSTGRES_USERNAME }} --build-arg POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} --build-arg POSTGRES_DB_PLATFORM=${{ secrets.POSTGRES_DB_PLATFORM }} --build-arg REDIS_HOST=${{ secrets.REDIS_HOST }} --build-arg REDIS_PORT=${{ secrets.REDIS_PORT }} --build-arg MAIL_HOST=${{ secrets.MAIL_HOST }} --build-arg MAIL_PORT=${{ secrets.MAIL_PORT }} --build-arg MAIL_USERNAME=${{ secrets.MAIL_USERNAME }} --build-arg MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }} -t devjasper0906/nest-core:${{ env.COMMIT_HASH }} --platform linux/amd64 .
          
          docker push devjasper0906/nest-core:${{ env.COMMIT_HASH }}